[package]
name = "pngsecret"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
structopt = "0.3.26"

[profile.release]
strip = true
codegen-units = 1
opt-level = 3
lto = true
panic = "abort"
